import assert from 'node:assert/strict';
import {mkdtemp,copyFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {runInNewContext} from 'node:vm';
import {readdir} from 'node:fs/promises';
const root=dirname(fileURLToPath(import.meta.url));
const dir=await mkdtemp(join(tmpdir(),'official-site-check-'));
try{
 for(const file of ['build.mjs','index.html','style.css','motion.js','app-icon.png'])await copyFile(join(root,file),join(dir,file));
 const run=vars=>spawnSync(process.execPath,[join(dir,'build.mjs')],{env:{...process.env,SITE_URL:'',WEB_APP_URL:'',VERCEL_ENV:'preview',...vars},encoding:'utf8'});
 assert.equal(run({}).status,0);
 let html=await readFile(join(dir,'dist/index.html'),'utf8');
 assert.equal((html.match(/data-web-app-url=""/g)||[]).length,2);
 assert.equal((html.match(/敬请期待/g)||[]).length,2);
 assert.equal((html.match(/aria-disabled="true"/g)||[]).length,2);
 assert.ok(html.includes('noindex,follow'));
 assert.ok(html.includes(`id="copyright-year">${new Date().getFullYear()}`));
 assert.equal(run({VERCEL_ENV:'production'}).status,1);
 assert.equal(run({WEB_APP_URL:'javascript:alert(1)'}).status,1);
 assert.equal(run({WEB_APP_URL:'https://user:password@example.com'}).status,1);
 assert.equal(run({VERCEL_ENV:'production',SITE_URL:'https://example.com',WEB_APP_URL:'https://app.example.com/research?a=1&b=2'}).status,0);
 html=await readFile(join(dir,'dist/index.html'),'utf8');
 assert.equal((html.match(/data-web-app-url="https:\/\/app.example.com\/research\?a=1&amp;b=2"/g)||[]).length,2);
 assert.ok(!html.includes('敬请期待'));
 assert.equal((html.match(/<span class="entry-label">进入网页版<\/span>/g)||[]).length,2);
 assert.ok(!html.includes('aria-disabled="true"'));
 assert.ok(!html.includes('网页版地址待接入'));
 assert.ok(!html.includes('目前本站的网页版入口尚未接入'));
 assert.ok(html.includes('rel="canonical" href="https://example.com/"'));
 assert.ok((await readFile(join(dir,'dist/sitemap.xml'),'utf8')).includes('<loc>https://example.com/</loc>'));
 assert.deepEqual((await readdir(join(dir,'dist'))).sort(),['app-icon.png','index.html','motion.js','robots.txt','sitemap.xml','style.css']);
 const motion=await readFile(join(root,'motion.js'),'utf8');
 const binding=motion.slice(motion.indexOf("document.querySelectorAll('.web-entry')"));
 const navigations=[];const listeners=[];
 const entries=['','https://app.example.com/research'].map(webAppUrl=>({dataset:{webAppUrl},addEventListener:(_,handler)=>listeners.push(handler)}));
 runInNewContext(binding,{document:{querySelectorAll:()=>entries},window:{location:{assign:url=>navigations.push(url)}}});
 listeners[0]();assert.deepEqual(navigations,[]);
 listeners[1]();assert.deepEqual(navigations,['https://app.example.com/research']);
 assert.equal(run({}).status,0);
 assert.ok(!(await readdir(join(dir,'dist'))).includes('sitemap.xml'));
 assert.ok(!(await readFile(join(dir,'dist/index.html'),'utf8')).includes('app.example.com'));
 console.log('通过：空入口、已配置双入口、HTML 转义、无效 URL、生产域名、年份与索引配置。');
}finally{await rm(dir,{recursive:true,force:true});}
